import { useState } from "react";
import { CritiqueResult, VictimType, BrutalityLevel } from "../types";
import { Copy, Check, Share2, Award, Zap, AlertCircle, FileText, Download, Printer, Clock, FileDown, Eye, X } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

interface ReportCardProps {
  key?: string;
  result: CritiqueResult;
  victimType: VictimType;
  brutality: BrutalityLevel;
  onSaveToHistory?: () => void;
  isSaved?: boolean;
  theme?: "dark" | "clinical";
}

export default function ReportCard({ 
  result, 
  victimType, 
  brutality, 
  onSaveToHistory, 
  isSaved,
  theme = "dark" 
}: ReportCardProps) {
  const [copiedQuote, setCopiedQuote] = useState(false);
  const [copiedFull, setCopiedFull] = useState(false);
  const [shareStatus, setShareStatus] = useState<string | null>(null);
  const [showExportModal, setShowExportModal] = useState(false);

  const isClinical = theme === "clinical";

  // Calculate Reading Time (average ~200 words per minute)
  const calculateReadingTime = () => {
    const textPieces = [
      result.verdict,
      result.killerQuote,
      ...result.roastPoints.map(p => `${p.title} ${p.description}`),
      ...result.remedyPoints.map(p => `${p.title} ${p.description}`)
    ].join(" ");
    const words = textPieces.trim().split(/\s+/).filter(Boolean).length;
    return Math.max(1, Math.ceil(words / 200));
  };

  const readingTime = calculateReadingTime();

  // Sentiment analysis based on strategic score and verdict markers
  const getSentimentTag = () => {
    const score = result.strategicScore;
    const verdictLower = result.verdict.toLowerCase();
    
    const isPositive = score >= 60 || verdictLower.includes("polish") || verdictLower.includes("decent") || verdictLower.includes("good") || verdictLower.includes("premium");
    const isCritical = score < 35 || verdictLower.includes("disaster") || verdictLower.includes("cliché") || verdictLower.includes("cliche") || verdictLower.includes("fatal") || verdictLower.includes("brutal");
    
    if (isPositive) {
      return {
        label: "Positive",
        colorClass: isClinical 
          ? "bg-emerald-50 border-emerald-200 text-emerald-800" 
          : "bg-emerald-500/10 border-emerald-500/20 text-emerald-400"
      };
    } else if (isCritical) {
      return {
        label: "Critical",
        colorClass: isClinical 
          ? "bg-rose-50 border-rose-200 text-rose-800" 
          : "bg-rose-500/10 border-rose-500/20 text-rose-400"
      };
    } else {
      return {
        label: "Neutral",
        colorClass: isClinical 
          ? "bg-amber-50 border-amber-200 text-amber-800" 
          : "bg-amber-500/10 border-amber-500/20 text-amber-400"
      };
    }
  };

  const sentiment = getSentimentTag();

  const handleCopyQuote = async () => {
    const textToCopy = `BrutalAI Verdict: "${result.verdict}"\n"${result.killerQuote}"\n\nGet roasted & strategized by BrutalAI: ${window.location.origin}`;
    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopiedQuote(true);
      setTimeout(() => setCopiedQuote(false), 2000);
    } catch (err) {
      console.error("Failed to copy", err);
    }
  };

  const handleCopyFullReport = async () => {
    const roastSection = result.roastPoints.map((p) => `- ${p.title}: ${p.description}`).join("\n");
    const remedySection = result.remedyPoints.map((p) => `- ${p.title}: ${p.description}`).join("\n");
    const fullText = `=== BRUTAL.AI DIAGNOSTIC REPORT ===
Category: ${victimType.toUpperCase()} | Mode: ${brutality.toUpperCase()}
Verdict: ${result.verdict}
Strategic Score: ${result.strategicScore}/100

" ${result.killerQuote} "

--- THE TEARDOWN ---
${roastSection}

--- THE TREATMENT ---
${remedySection}

Roasted with love at ${window.location.origin}`;

    try {
      await navigator.clipboard.writeText(fullText);
      setCopiedFull(true);
      setTimeout(() => setCopiedFull(false), 2000);
    } catch (err) {
      console.error("Failed to copy full report", err);
    }
  };

  const handleDownloadReport = () => {
    const roastSection = result.roastPoints.map((p, idx) => `### 0${idx + 1}. ${p.title}\n${p.description}`).join("\n\n");
    const remedySection = result.remedyPoints.map((p, idx) => `### ✓ ${p.title}\n${p.description}`).join("\n\n");
    
    const markdownContent = `# BRUTAL.AI DIAGNOSTIC REPORT
**Verdict**: ${result.verdict}
**Category**: ${victimType.toUpperCase()}
**Diagnostic Mode**: ${brutality.toUpperCase()}
**Strategic Score (Maturity)**: ${result.strategicScore}/100

> "${result.killerQuote}"

---

## 💀 THE TEARDOWN
${roastSection}

---

## 💊 THE REMEDY (STRATEGIC TREATMENT)
${remedySection}

---
*Generated by BrutalAI - Elite Cultural Critic & Brand Doctor*
${window.location.origin}
`;

    const blob = new Blob([markdownContent], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `BrutalAI-Report-${victimType}-${result.verdict.replace(/\s+/g, "-")}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadTxt = () => {
    const roastSection = result.roastPoints.map((p, idx) => `0${idx + 1}. ${p.title}\n${p.description}`).join("\n\n");
    const remedySection = result.remedyPoints.map((p, idx) => `✓ ${p.title}\n${p.description}`).join("\n\n");
    
    const txtContent = `=== BRUTAL.AI DIAGNOSTIC REPORT ===
Verdict: ${result.verdict}
Category: ${victimType.toUpperCase()}
Diagnostic Mode: ${brutality.toUpperCase()}
Strategic Score: ${result.strategicScore}/100

"${result.killerQuote}"

--------------------------------------------
💀 THE TEARDOWN
--------------------------------------------
${roastSection}

--------------------------------------------
💊 THE REMEDY (STRATEGIC TREATMENT)
--------------------------------------------
${remedySection}

--------------------------------------------
Generated by BrutalAI - Elite Cultural Critic & Brand Doctor
${window.location.origin}
`;

    const blob = new Blob([txtContent], { type: "text/plain;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `BrutalAI-Report-${victimType}-${result.verdict.replace(/\s+/g, "-")}.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = async () => {
    const payload = {
      victimType,
      brutality,
      result
    };
    
    try {
      const base64Data = btoa(unescape(encodeURIComponent(JSON.stringify(payload))));
      const shareUrl = `${window.location.origin}${window.location.pathname}?share=${base64Data}`;
      
      if (navigator.share) {
        await navigator.share({
          title: `BrutalAI Diagnosis: ${result.verdict}`,
          text: `"${result.killerQuote}" - Read the full roast and remedy:`,
          url: shareUrl,
        });
        setShareStatus("Shared via Browser!");
        setTimeout(() => setShareStatus(null), 2500);
      } else {
        await navigator.clipboard.writeText(shareUrl);
        setShareStatus("Shareable Link Copied!");
        setTimeout(() => setShareStatus(null), 2500);
      }
    } catch (err) {
      console.error("Failed to share", err);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  // Strategic score color coding
  const getScoreColor = (score: number) => {
    if (score < 30) return "text-[#ff451a] border-[#ff451a] bg-[#ff451a]/10";
    if (score < 60) return "text-amber-500 border-amber-500/40 bg-amber-500/10";
    return "text-emerald-400 border-emerald-500/40 bg-emerald-500/10";
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="space-y-6 print-container"
    >
      {/* Dynamic Summary Panel */}
      <div className={`border transition-colors duration-200 rounded-lg p-6 flex flex-col md:flex-row md:items-center justify-between gap-6 ${
        isClinical 
          ? "bg-white border-neutral-300 text-neutral-900 shadow-sm" 
          : "bg-[#121214] border-neutral-800 text-white"
      }`}>
        <div className="space-y-2.5 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <span className={`text-[10px] font-mono tracking-widest uppercase px-2 py-0.5 rounded border transition-colors duration-200 ${
              isClinical 
                ? "bg-neutral-100 border-neutral-200 text-neutral-600" 
                : "bg-neutral-900 border-neutral-800 text-neutral-400"
            }`}>
              Diagnostic Verdict
            </span>
            <span className="text-[10px] font-mono tracking-widest uppercase text-[#ff451a]">
              Category: {victimType}
            </span>
            {/* Reading Time Estimator */}
            <span className={`text-[10px] font-mono tracking-tight px-2 py-0.5 rounded border flex items-center gap-1 transition-colors duration-200 ${
              isClinical
                ? "bg-neutral-50 border-neutral-200 text-neutral-600"
                : "bg-neutral-950 border-neutral-800 text-neutral-400"
            }`}>
              <Clock className="h-3 w-3 text-[#ff451a]" />
              {readingTime} min read
            </span>
            {/* Sentiment Tag Indicator */}
            <span className={`text-[10px] font-mono font-black tracking-widest uppercase px-2.5 py-0.5 rounded border ${sentiment.colorClass}`}>
              {sentiment.label} Tone
            </span>
          </div>

          <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
            <h2 className={`text-2xl sm:text-3xl font-extrabold tracking-tight leading-none transition-colors duration-200 ${
              isClinical ? "text-neutral-900" : "text-white"
            }`}>
              {result.verdict}
            </h2>
          </div>

          <p className={`text-xs font-sans transition-colors duration-200 ${
            isClinical ? "text-neutral-600" : "text-neutral-400"
          }`}>
            Diagnostic run complete. Save to history or click export to choose formats.
          </p>
        </div>

        {/* Score Ring Meter */}
        <div className={`flex items-center gap-4 shrink-0 pl-0 md:pl-6 border-l transition-colors duration-200 ${
          isClinical ? "border-neutral-200" : "border-neutral-800/80"
        }`}>
          <div className={`h-20 w-20 rounded-full border-4 flex flex-col items-center justify-center font-mono ${getScoreColor(result.strategicScore)}`}>
            <span className="text-2xl font-black">{result.strategicScore}</span>
            <span className="text-[9px] uppercase tracking-wider text-neutral-400 -mt-1">Maturity</span>
          </div>
          <div>
            <div className={`text-xs font-mono font-bold transition-colors duration-200 ${isClinical ? "text-neutral-800" : "text-neutral-300"}`}>Strategic Score</div>
            <p className="text-[11px] text-neutral-500 leading-snug max-w-[150px] mt-1 font-sans">
              {result.strategicScore < 30
                ? "Severely critical. Immediate structural pivot advised."
                : result.strategicScore < 60
                ? "Mediocre. Full of clichés, but salvageable."
                : "Decent foundations, requires polishing."}
            </p>
          </div>
        </div>
      </div>

      {/* Killer Quote Poster (Ultra-Shareable) */}
      <div className={`relative overflow-hidden border-2 border-[#ff451a] p-6 sm:p-8 flex flex-col items-center justify-center text-center rounded-lg shadow-2xl transition-colors duration-200 ${
        isClinical ? "bg-neutral-50" : "bg-neutral-950"
      }`}>
        {/* Background texture line */}
        <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-transparent via-[#ff451a] to-transparent opacity-80" />
        
        <span className={`font-mono text-xs uppercase tracking-widest text-[#ff451a] mb-4 flex items-center gap-1.5 border px-2.5 py-1 rounded transition-colors duration-200 ${
          isClinical ? "bg-white border-neutral-200" : "bg-neutral-900 border-[#ff451a]/20"
        }`}>
          <Zap className="h-3 w-3 fill-[#ff451a] text-[#ff451a]" /> BrutalAI Killer Quote
        </span>
        
        <blockquote className={`text-lg sm:text-xl font-medium tracking-tight max-w-2xl leading-relaxed italic transition-colors duration-200 ${
          isClinical ? "text-neutral-900" : "text-neutral-100"
        }`}>
          &ldquo;{result.killerQuote}&rdquo;
        </blockquote>

        <div className="flex flex-wrap items-center justify-center gap-3 mt-6">
          <button
            type="button"
            id="btn-share-quote"
            onClick={handleCopyQuote}
            className="text-xs font-mono font-black bg-[#ff451a] hover:bg-[#ff3200] text-black px-4 py-2 rounded flex items-center gap-1.5 transition-all active:scale-95 cursor-pointer"
          >
            {copiedQuote ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copiedQuote ? "Copied Quote!" : "Copy Quote"}</span>
          </button>
          
          <button
            type="button"
            id="btn-copy-report"
            onClick={handleCopyFullReport}
            className={`text-xs font-mono font-bold border px-4 py-2 rounded flex items-center gap-1.5 transition-all active:scale-95 cursor-pointer ${
              isClinical
                ? "bg-white border-neutral-300 text-neutral-800 hover:bg-neutral-100"
                : "bg-neutral-900 border-neutral-800 text-neutral-300 hover:text-white hover:border-neutral-700"
            }`}
            title="Copy entire roasted analysis text to your clipboard"
          >
            {copiedFull ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copiedFull ? "Report Copied!" : "Copy Full Report"}</span>
          </button>

          {/* Web Share Trigger */}
          <button
            type="button"
            id="btn-web-share"
            onClick={handleShare}
            className="text-xs font-mono font-black bg-neutral-900 border border-[#ff451a]/40 text-neutral-200 hover:text-white hover:bg-neutral-800 px-4 py-2 rounded flex items-center gap-1.5 transition-all active:scale-95 cursor-pointer"
          >
            {shareStatus ? <Check className="h-3.5 w-3.5 text-[#ff451a]" /> : <Share2 className="h-3.5 w-3.5 text-[#ff451a]" />}
            <span>{shareStatus || "Share Audit Link"}</span>
          </button>
        </div>
      </div>

      {/* Structured Report Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Roast Section */}
        <div className={`border rounded-lg p-5 space-y-4 transition-colors duration-200 ${
          isClinical ? "bg-white border-neutral-300" : "bg-[#121214] border-neutral-800"
        }`}>
          <div className={`flex items-center gap-2 pb-3 border-b transition-colors duration-200 ${
            isClinical ? "border-neutral-200" : "border-neutral-800"
          }`}>
            <div className="h-7 w-7 rounded bg-[#ff451a]/10 flex items-center justify-center">
              <AlertCircle className="h-4 w-4 text-[#ff451a]" />
            </div>
            <div>
              <h3 className={`text-sm font-mono font-black uppercase tracking-wider transition-colors duration-200 ${
                isClinical ? "text-neutral-900" : "text-white"
              }`}>
                The Teardown
              </h3>
              <p className="text-[10px] text-neutral-500 font-sans">
                Critique of redundant clichés and fatal flaws
              </p>
            </div>
          </div>

          <div className="space-y-4">
            {result.roastPoints.map((point, idx) => (
              <div key={idx} className="space-y-1">
                <h4 className={`text-xs font-mono font-bold flex items-center gap-2 transition-colors duration-200 ${
                  isClinical ? "text-neutral-800" : "text-neutral-200"
                }`}>
                  <span className="text-[#ff451a] font-black">0{idx + 1}.</span>
                  {point.title}
                </h4>
                <p className={`text-xs font-sans leading-relaxed pl-5 transition-colors duration-200 ${
                  isClinical ? "text-neutral-600" : "text-neutral-400"
                }`}>
                  {point.description}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Remedy Section */}
        <div className={`border rounded-lg p-5 space-y-4 transition-colors duration-200 ${
          isClinical ? "bg-white border-neutral-300" : "bg-[#121214] border-neutral-800"
        }`}>
          <div className={`flex items-center gap-2 pb-3 border-b transition-colors duration-200 ${
            isClinical ? "border-neutral-200" : "border-neutral-800"
          }`}>
            <div className="h-7 w-7 rounded bg-emerald-500/10 flex items-center justify-center">
              <Award className="h-4 w-4 text-emerald-400" />
            </div>
            <div>
              <h3 className={`text-sm font-mono font-black uppercase tracking-wider transition-colors duration-200 ${
                isClinical ? "text-neutral-900" : "text-white"
              }`}>
                The Remedy
              </h3>
              <p className="text-[10px] text-neutral-500 font-sans">
                Strategic prescriptive solutions &amp; pivots
              </p>
            </div>
          </div>

          <div className="space-y-4">
            {result.remedyPoints.map((point, idx) => (
              <div key={idx} className="space-y-1">
                <h4 className={`text-xs font-mono font-bold flex items-center gap-2 transition-colors duration-200 ${
                  isClinical ? "text-neutral-800" : "text-neutral-200"
                }`}>
                  <span className="text-emerald-400 font-black">✓</span>
                  {point.title}
                </h4>
                <p className={`text-xs font-sans leading-relaxed pl-5 transition-colors duration-200 ${
                  isClinical ? "text-neutral-600" : "text-neutral-400"
                }`}>
                  {point.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Action panel: Save, Download Report, and Print Utility */}
      <div className="flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-neutral-800/20">
        <div className="flex items-center gap-2">
          {/* Export Options Trigger button */}
          <button
            type="button"
            id="btn-open-export-modal"
            onClick={() => setShowExportModal(true)}
            className={`px-4 py-2.5 text-xs font-mono font-black border rounded transition-all flex items-center gap-1.5 cursor-pointer active:scale-95 bg-[#ff451a] border-[#ff451a] hover:bg-[#ff3200] text-black shadow-lg shadow-[#ff451a]/10`}
            title="Open Export Options to download as TXT, MD, or Simplified PDF"
          >
            <FileDown className="h-3.5 w-3.5" />
            <span>Export Report Options...</span>
          </button>

          {/* Quick Print PDF Button */}
          <button
            type="button"
            id="btn-quick-print-pdf"
            onClick={handlePrint}
            className={`px-4 py-2.5 text-xs font-mono font-bold border rounded transition-all flex items-center gap-1.5 cursor-pointer active:scale-95 ${
              isClinical
                ? "bg-white hover:bg-neutral-100 border-neutral-300 text-neutral-800"
                : "bg-neutral-900 hover:bg-neutral-800 text-neutral-200 border-neutral-800"
            }`}
            title="Generate print setup or save as PDF document"
          >
            <Printer className="h-3.5 w-3.5 text-[#ff451a]" />
            <span>Print PDF</span>
          </button>
        </div>

        {onSaveToHistory && (
          <button
            type="button"
            id="btn-archive-report"
            onClick={onSaveToHistory}
            disabled={isSaved}
            className={`px-4 py-2.5 text-xs font-mono font-bold border rounded transition-all flex items-center gap-2 ${
              isSaved
                ? "bg-neutral-900 border-neutral-800 text-neutral-500 cursor-default"
                : "bg-neutral-800 hover:bg-neutral-700 text-neutral-200 border-neutral-700 cursor-pointer active:scale-95"
            }`}
          >
            <FileText className="h-3.5 w-3.5" />
            <span>{isSaved ? "Saved to Terminal History" : "Save to History"}</span>
          </button>
        )}
      </div>

      {/* Export Options Overlay Modal */}
      <AnimatePresence>
        {showExportModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowExportModal(false)}
              className="absolute inset-0 bg-black/85 backdrop-blur-sm cursor-pointer"
            />

            {/* Modal Dialog Box */}
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 15 }}
              className={`relative z-10 w-full max-w-md border rounded-xl shadow-2xl overflow-hidden p-6 transition-colors duration-200 ${
                isClinical
                  ? "bg-white border-neutral-300 text-neutral-900"
                  : "bg-[#121214] border-neutral-800 text-white"
              }`}
            >
              <div className="flex items-center justify-between pb-4 border-b border-neutral-800/10 mb-4">
                <div className="flex items-center gap-2">
                  <FileDown className="h-5 w-5 text-[#ff451a]" />
                  <h3 className="font-mono font-black text-sm uppercase tracking-wider">
                    Export Options
                  </h3>
                </div>
                <button
                  type="button"
                  id="btn-close-export"
                  onClick={() => setShowExportModal(false)}
                  className={`p-1.5 rounded-md hover:bg-neutral-800/10 cursor-pointer transition-colors`}
                >
                  <X className="h-4 w-4" />
                </button>
              </div>

              <p className={`text-xs font-sans leading-relaxed mb-6 ${
                isClinical ? "text-neutral-600" : "text-neutral-400"
              }`}>
                Save your strategic diagnostic evaluation locally. Choose between structured text formats or trigger an offline paper-friendly high-contrast layout.
              </p>

              {/* Grid of choices */}
              <div className="space-y-3">
                {/* 1. TXT File Choice */}
                <button
                  type="button"
                  id="export-choice-txt"
                  onClick={() => {
                    handleDownloadTxt();
                    setShowExportModal(false);
                  }}
                  className={`w-full p-3.5 border rounded-lg text-left flex items-start gap-3 transition-all cursor-pointer ${
                    isClinical
                      ? "bg-neutral-50 hover:bg-neutral-100 border-neutral-200 hover:border-neutral-300"
                      : "bg-neutral-900/60 hover:bg-neutral-900 border-neutral-800 hover:border-neutral-700"
                  }`}
                >
                  <div className="h-8 w-8 shrink-0 rounded bg-blue-500/10 flex items-center justify-center">
                    <FileText className="h-4 w-4 text-blue-400" />
                  </div>
                  <div>
                    <h4 className="text-xs font-mono font-bold">Download Plain Text (.txt)</h4>
                    <p className={`text-[10px] font-sans mt-0.5 ${
                      isClinical ? "text-neutral-500" : "text-neutral-400"
                    }`}>
                      Standard plain-text document ideal for simple notes and scratchpads.
                    </p>
                  </div>
                </button>

                {/* 2. MD File Choice */}
                <button
                  type="button"
                  id="export-choice-md"
                  onClick={() => {
                    handleDownloadReport();
                    setShowExportModal(false);
                  }}
                  className={`w-full p-3.5 border rounded-lg text-left flex items-start gap-3 transition-all cursor-pointer ${
                    isClinical
                      ? "bg-neutral-50 hover:bg-neutral-100 border-neutral-200 hover:border-neutral-300"
                      : "bg-neutral-900/60 hover:bg-neutral-900 border-neutral-800 hover:border-neutral-700"
                  }`}
                >
                  <div className="h-8 w-8 shrink-0 rounded bg-[#ff451a]/10 flex items-center justify-center">
                    <Download className="h-4 w-4 text-[#ff451a]" />
                  </div>
                  <div>
                    <h4 className="text-xs font-mono font-bold">Download Markdown (.md)</h4>
                    <p className={`text-[10px] font-sans mt-0.5 ${
                      isClinical ? "text-neutral-500" : "text-neutral-400"
                    }`}>
                      Rich markup formatting perfect for GitHub, Notion, or text editors.
                    </p>
                  </div>
                </button>

                {/* 3. PDF print Choice */}
                <button
                  type="button"
                  id="export-choice-pdf"
                  onClick={() => {
                    setShowExportModal(false);
                    // Slight timeout to let modal transition clear
                    setTimeout(handlePrint, 350);
                  }}
                  className={`w-full p-3.5 border rounded-lg text-left flex items-start gap-3 transition-all cursor-pointer ${
                    isClinical
                      ? "bg-neutral-50 hover:bg-neutral-100 border-neutral-200 hover:border-neutral-300"
                      : "bg-neutral-900/60 hover:bg-neutral-900 border-neutral-800 hover:border-neutral-700"
                  }`}
                >
                  <div className="h-8 w-8 shrink-0 rounded bg-emerald-500/10 flex items-center justify-center">
                    <Printer className="h-4 w-4 text-emerald-400" />
                  </div>
                  <div>
                    <h4 className="text-xs font-mono font-bold">Simplified PDF Document</h4>
                    <p className={`text-[10px] font-sans mt-0.5 ${
                      isClinical ? "text-neutral-500" : "text-neutral-400"
                    }`}>
                      Formats a clean printable layout and triggers your system print-to-PDF dialog.
                    </p>
                  </div>
                </button>
              </div>

              <div className="mt-6 pt-4 border-t border-neutral-800/10 flex justify-end">
                <button
                  type="button"
                  id="btn-cancel-export"
                  onClick={() => setShowExportModal(false)}
                  className={`px-4 py-2 rounded text-xs font-mono font-bold cursor-pointer hover:bg-neutral-800/10`}
                >
                  Cancel
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
